# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bill Zangardi - Android Software Engineer
email: bill.zangardi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Bill Zangardi is a Software Engineer focusing on Android development, currently residing in Philadelphia, Pa. Bill is currently an Android Developer at Elsevier Inc and Rappid Development, LLC.
url: "http://billzangardi.me/blog" # the base hostname & protocol for your site
twitter_username: biller_lite
github_username:  billzangardi

# Build settings
markdown: kramdown
